### ISSUE TITLE
change "remote user"

### ISSUE THREAD

**Issue by marcelozabaljauregui** [owncloud/richdocuments#114]
Tengo instalado el owncloud 9.1.1 con Collabora Online 1.1.4. con LDAP para validar los usuarios
Cuando voy la "actividad" del usuario despues de modificar un archivo tengo la leyenda:
"cambiado por usuario remoto" 
![owncloud-remoteuser](https://cloud.githubusercontent.com/assets/18450145/18873838/a124546e-8497-11e6-8c2d-8d686b7ca5c8.png)
Esto es correcto o estoy omitiendo alguna configuración entre el owncloud y el collabora online?
Saludos.

**Comment by MariusBluem** [comment]
Buenos días 😜 @marcelozabaljauregui ... sería bueno si pudiera usar Inglés en el futuro.

I have now translated your request, so that everybody is able to read - and report back 😉 

He has installed ownCloud 9.1.1 and is using Collabora Online 1.1.4 :) ...LDAP is his user backend.
The activity tab is showing him a "changed by a remote user" after a user has changed his file.

Now he wants to ask whether this is the correct behavior or if this is maybe a issue between the connection of ownCloud and Collabora Online :)

**Comment by GOEBELJOERG** [comment]
I have the same error with owncloud normal users (not admin users). When a document was changed then the detail section of a file cannot display the correct user name - but "remote User" will be displayed. 
OwnCloud 9.1.6.2 with ldap and rich documents 1.1.22 is installed.

**Comment by wschaft** [comment]
Same error here with ownCloud 10.0.3, Shibboleth users and rich documents 1.1.26

**Comment by davidsgn** [comment]
same error here owncloud 10.0.2.1, LDAP users and Collabora 3. It seems that editing online documents, the engine can't detect/retrieve which user is editing the file.

**Comment by PVince81** [comment]
In general if this app was using the Node API (or even the View) the hooks should already be triggered for the currently logged in user, so that the activity app can find the correct user.

To fix this one should ideally debug into the activity app and check https://github.com/owncloud/activity/blob/master/lib/FilesHooks.php#L117 to see what stack leads there and find out why the owner is wrong.

**Comment by pmaier1** [comment]
Fixed by https://github.com/owncloud/richdocuments/pull/260
