### ISSUE TITLE
Where can we find the Dockerfile that makes the docker image?

### ISSUE THREAD

**Issue by pierreozoux** [owncloud/richdocuments#131]
Sorry to ask the question here, but I don't know where to find there issue tracker.

**Comment by timar** [comment]
We did not publish the Dockerfile that was used to create collabora/code, because the binary package repositories are not public. However, we have a repository on github, which has the scripts and Dockerfiles we used, but the required secret URL part is available only for Collabora partners.
See: https://github.com/CollaboraOnline/Docker
