### ISSUE TITLE
Editor don't work, but I can see the file

### ISSUE THREAD

**Issue by claudio4** [owncloud/richdocuments#136]
When I open a file i can only see the content, but not edit it.

Look like a front-end error.

I use Collabora Office 5.1-11 and richdocuments 1.1.13.

The browser's console show this errors.

<img src="https://i.claudio4.com/i1Qmmt.png">

**Comment by timar** [comment]
Hi @claudio4 

The errors in browser console are not related. The problem is, that UserCanWrite property of WOPI CheckFileInfo is boolean in the WOPI standard, yet we sent a string "true" and expected a string "true" on the other side. This was fixed, so richdocuments 1.1.13 now sends a boolean value. But in your setup the other side still expects a string. You have to update.
