### ISSUE TITLE
Headless mode support // Without Docker

### ISSUE THREAD

**Issue by HLFH** [owncloud/richdocuments#137]
Hi,

[Here](https://wiki.documentfoundation.org/Development/HeadlessBuild), I understood that LibreOffice has a headless mode that can be built without linking to X, cairo, GUI toolkits. Nevertheless, it seems it's broken in master.

And ownCloud & Nextcloud support Collabora Office [but only with the bloated Docker](https://nextcloud.com/collaboraonline/).

I'm following ownCloud and Nextcloud since the beginning, and I would be quite sad if you decide not to offer - when Collabora Office will be production-ready - a proper way to set up Collabora Office **without Docker** and **without linking to X, cairo, GUI toolkits**.

Is that planned? Or what are the showstoppers?

**Comment by MariusBluem** [comment]
I think this is depending on what you are trying to deploy. For the "normal" user, you are right - there is only the Docker Image (and the VM) ... if you want something more customized ... you may need to build it from scratch - that's possible - but not something I would recommend to somebody who just wants to use it for home use 🙈

If you are an Enterprise user, you may want to consider about using an enterprise plan, which can include Collabora Online in some contracts ... which is not exactly the same as CODE (...which is more meant for developers, testers and home-users) and the Docker Image we are talking about. 

For example, Nextcloud is providing Collabora Online support with its Enterprise-Support subscription: https://nextcloud.com/enterprise/ ... **with** custom deployment for your needs ;)

**Comment by HLFH** [comment]
Hi. Thanks for the answer. I am an Arch Linux user, so, I like to build it from scratch. When you say "that's possible" to build it from scratch, **are you sure that it's WITHOUT the X, cairo, GUI toolkits dependencies?** and, do you have a link? In a server environment, I don't want a bloated LibreOffice Online but a streamlined LibreOffice Online/Collabora Office. If I can't use it for home/pro use in a decent manner (without Docker & VM AND without X, cairo, GUI toolkits dependencies), I wouldn't be able to recommend Collabora Office to enterprises I meet or work with.

**Comment by MariusBluem** [comment]
This is really something you should talk about with the Collabora Office guys, because this is not something depending on Nextcloud or ownCloud directly ... this repository is only about the connector app, which is connecting Nextcloud/ownCloud with the Collabora Online server. The Collabora Online - server is developed and maintained by the Collabora Productivity guys, which we are working **with** here - but if you want to learn something about building the server, you should definitely contact them directly, because I think they can help you there best. Try it here: https://www.collaboraoffice.com/contact-sales/ ... of course you are also welcome to contact the sales team of the cloud software which is providing Collabora Online support directly 😉

> EDIT: and it does not seem you have your own richdocuments repo. Do you plan to add it?

If you mean Nextcloud with **you**, I have to say, that I don't know about the current state of that. Nextcloud GmbH does provide Enterprise plans with Collabora Online - and for that reason I think we are planning to add/fork/maintain it 😉🙈

**Comment by HLFH** [comment]
Ok I'll contact them and I'll come back to this issue.

And if I don't find any answer, I'll switch  back to MS Office.

**Comment by enoch85** [comment]
+1 for this. Would be soo much easier, and better.

**Comment by HLFH** [comment]
I've sent two emails. I hope we'll get an answer in the coming week.

**Comment by hregnier** [comment]
I found this https://gist.github.com/m-jowett/0f28bff952737f210574fc3b2efaa01a
I give it to my co-worker for installing, after some days, it works now.
Hope it helps!

**Comment by HLFH** [comment]
https://aur.archlinux.org/packages/collabora-online-server-nodocker/ solved the issue on Arch Linux.
