### ISSUE TITLE
Re-enable tests on `latest` after the 10.5.0 Core release

### ISSUE THREAD

**Issue by micbar** [owncloud/richdocuments#348]
# Description
- [x] disabled the tests on `latest` due to #347 

## Tasks
- [x] re enable `latest` tests after successful core release of 10.5.0

**Comment by phil-davis** [comment]
Side note: there are other repos that will need this done also, and I am too lazy right now to find them :) 
Look for repos that have core min-version 10.5 and re-enable acceptance tests against `latest`

**Comment by phil-davis** [comment]
Fixed in #352 

Also fixed in other repos:
https://github.com/owncloud/admin_audit/pull/343
https://github.com/owncloud/files_classifier/pull/366
https://github.com/owncloud/files_lifecycle/pull/269
https://github.com/owncloud/firewall/pull/652
https://github.com/owncloud/ransomware_protection/pull/244
https://github.com/owncloud/testing/pull/154
https://github.com/owncloud/windows_network_drive/pull/303
https://github.com/owncloud/workflow/pull/245
