### ISSUE TITLE
Revision History broken

### ISSUE THREAD

**Issue by theheyon** [owncloud/richdocuments#415]
Hey on there!

Revision History seems to be broken ((

![image](https://user-images.githubusercontent.com/79450887/125823094-bd4c6845-ddc9-48d9-99fd-fa41ce76895e.png)

System:
CODE running on Ubuntu 18.04.4 LTS
LOOLWSD 6.4.9
LOKit Collabora Office 6.4-39
Collabora Online app 2.5.0
ownCloud 10.7.0

Same issues here:
https://github.com/owncloud/richdocuments/issues/275
https://github.com/owncloud/richdocuments/issues/222

Maybe, a way to fix from NC:
https://github.com/nextcloud/richdocuments/issues/9
https://github.com/nextcloud/richdocuments/pull/27

**Comment by theheyon** [comment]
/js/documents.js:

![image](https://user-images.githubusercontent.com/79450887/126013590-be9a689e-d336-4639-b566-ce5d25cdf6a4.png)

maybe, someone forgot about this? )
or OC10x still not supports a feature?

**Comment by theheyon** [comment]
maybe, versioning API could be used instead files_versions app itself?

https://doc.owncloud.com/server/developer_manual/webdav_api/files_versions.html

**Comment by mrow4a** [comment]
This is not an easy fix @hodyroff . The issue here is that we switched for version to META endpoint and DAV (Propfind/Copy/etc). This means, it would be impossible to access it that way from frontend. 

However, what can be done is what onlyoffice did. Backend integration. We just put a wrapper on top of oc10 versions, and access them directly. Thus implement our own controller here. The limitation would be that we probably could be only seeing contents of versions, but we cannot manage versions (restore/publish/dowload/etc), this would need to be done from versions tab in OC UI. Can probably be done via some button to redirect there 🤷🏻‍♂️ 

I think this is good solution as streamlines with OnlyOffice, and I would progress with it.
