### ISSUE TITLE
Release 3.0.0 for Guzzle7

### ISSUE THREAD

**Issue by phil-davis** [owncloud/richdocuments#472]
for guzzle7 core issue https://github.com/owncloud/core/issues/39387

to release with oC core 10.11

Note: release 2.8.0 should best happen first, to get the latest code released that will work with core 10.10 and earlier.

**Comment by jnweiger** [comment]
## 'Richdocuments' Test Plan

Template: https://github.com/owncloud/QA/tree/master/Server/Test_Plan_richdocuments.md

## Setup
<details><summary>Setup details (click to view)</summary>

* [ ] setup via `make_oc10_apps.sh richdocuments` 
    -> https://oc10110-richdocuments-300rc2-20220926.jw-qa.owncloud.works
</details>

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
occ a:e richdocuments | app gets enabled  | :heavy_checkmark:  |
occ a:dis richdocuments | app gets disabled |  :heavy_checkmark:  |
Configure wopi | connects via WOPI | :heavy_checkmark:  |
Smoke test text document | Basic editing works | :heavy_checkmark:  |
Smoke test spreadsheet | Basic editing works | :heavy_checkmark:  |
Smoke test impress | Basic editing works | :heavy_checkmark:  |
Smoke test impress | Full screen Presentation | :no_entry_sign:  | Firefox: Works. Chrome console log: Refused to display 'https://collabora.owncloud-demo.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
Smoke test drawing | Basic editing works | :heavy_checkmark:  |
enable pdfviewer | edit chooser popup allows choice | :heavy_checkmark:   |
Smoke test PDF | option collabora allows to add comments, then download | :heavy_checkmark:   |
Smoke test PDF | option files_pdfviewer works | :heavy_checkmark: |
enable texteditor | edit chooser popup allows choice | :heavy_checkmark:  |
Smoke test TXT | option collabora allows text editing | :heavy_checkmark:   |
Smoke test TXT | option files_textviewer works | :heavy_checkmark: |
Secure view | checkbox grayed out without ee license | :heavy_checkmark:  |
Secure view | sharing defaults to secure view | :heavy_checkmark:  |
Secure view | documents have watermark, cannot be downloaded | :heavy_checkmark:  |
Secure view | still works with invalid or expired license key, until disabled | :heavy_checkmark:  |


----

**Comment by jnweiger** [comment]
## Issues seen while testing

* [ ] https://github.com/owncloud/files_pdfviewer/issues/321

**Comment by jnweiger** [comment]
@timar QA passed from my side.
Ready for you to provide a signed final from here: https://github.com/owncloud/richdocuments/releases/tag/v3.0.0-rc.2

**Comment by jnweiger** [comment]
Final 3.0.0 is on github.
