### ISSUE TITLE
Not able to open documents on Safari Browser

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/richdocuments#476]
### Steps to reproduce
- Try to open a document on Safari browser (seen on version 15.6 (MacOS))

### Current behaviour 
<img width="989" alt="image" src="https://user-images.githubusercontent.com/33026403/187238249-a04cc934-7786-4883-a01b-6bf189922748.png">

**Comment by IljaN** [comment]
On a quick try we couldn't reproduce in damkencloud. It looks like a issue with content-security policy (CSP). Are there any special steps with regard to CSP which need to be done during config?

Are other browser working?

**Comment by NannaBarz** [comment]
Which version from collabora is installed? 
Is this from a customer and can we have a config report and a collabora coolwsd report?

**Comment by NannaBarz** [comment]
@ChrisEdS 
Which version from collabora is installed?
Is this from a customer and can we have a config report and a collabora coolwsd report?

**Comment by ChrisEdS** [comment]
I have more and more the opinion that this issue happens while working with a company proxy. I will close for now.

**Comment by xoxys** [comment]
Scenario: 

We have deployed ownCloud Web as a sidecar container to ownCloud in multiple deployments. This way ownCloud and ownCloud Web are running on different domains and a custom CSP for Collabora (and Onlyoffice) is required by oC Web to embed Collabora as a framework.

Problem:

Adding `connect-src 'self'` to the Collabora CSP is not sufficient because `wss` is not automatically included in `'self'` on some browsers, see https://github.com/w3c/webappsec-csp/issues/7 To fix this, we had to modify the CSP to `connect-src 'self' wss://collabora.example.org`. 

Why does this only affect Safari:

I'm not entirely sure, but for some reason Safari seems to be the only browser that connects to Collabora via web socket, while all other browsers (at least Chrome and FF) do not.
